[config]
reload_apps = false

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/tokens/colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "~/.config/matugen/templates/colors-rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.ghostty]
input_path = '~/.config/ghostty/auto/colors.txt'
output_path = '~/.config/ghostty/themes/Matugen'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.helix]
input_path = '~/.config/helix/colors.txt'
output_path = '~/.config/helix/themes/matugen.toml'
# Hot-reload helix config
post_hook = 'pkill -USR1 hx'

[templates.yazi]
input_path = '~/.config/yazi/config.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.hyprland]
input_path = '~/.config/hypr/colors_template.lua'
output_path = '~/.config/hypr/colors.lua'

[templates.dunst]
input_path = '~/.config/dunst/config_template.toml'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
