#!/usr/bin/env bash

# Copy tmux files
cp -aRv tmux/. ~/.tmux/
# Copy tmux config file
cp tmux/.tmux.conf ~/

# Copy nvim plugins
cp -aRv nvim/. ~/.config/nvim/

# Copy Ghostty config
cp -aRv ghostty/. ~/.config/ghostty/
