#!/usr/bin/env bash

# Copy tmux files
cp -aRv tmux/. $HOME/.tmux/

# Copy nvim plugins
cp -aRv nvim/. $HOME/.config/nvim/

# Copy Ghostty config
cp -aRv ghostty/. $HOME/.config/ghostty/

# Copy ZSHRC file
cp -v .zshrc $HOME/
