# theme = "catppuccin_macchiato"
theme = "gruvbox_dark_soft"

[editor]
middle-click-paste = false
shell = ["fish"]
line-number = "relative"
preview-completion-insert = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.file-picker]
hidden = false
deduplicate-links = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "warning"
