theme = "nord-night"

[editor]
middle-click-paste = false
shell = ["fish", "-c"]
line-number = "relative"
preview-completion-insert = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
deduplicate-links = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
C-l = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":rla"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':rla',
]
C-g = ":sh echo %sh{git show --no-patch --format='%%h \\(%%an: %%ar\\): %%s' (git blame -p %{buffer_name} -L%{cursor_line},+1 | head -1 | cut -d' ' -f1)}"

