# theme = "catppuccin_macchiato"
theme = "gruvbox_dark_soft"

[editor]
middle-click-paste = false
shell = ["fish", "-c"]
line-number = "relative"
preview-completion-insert = false
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
deduplicate-links = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
# Open git blame for current line
Cmd-b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
C-y = ":sh tmux new-window -n fx '~/.config/helix/yazi-picker.sh open'"
